_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: e9e916c0-4d7d-4ae1-abfa-3cf35847e4b5
name: "Eric Shell's White Label Application"
mail: ericjshell@gmail.com
slogan: ''
page:
  403: /node/1
  404: /node/2
  front: /node/3
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
